import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("word-counter", "routes/word-counter.tsx"),
  route("character-counter", "routes/character-counter.tsx"),
  route("case-converter", "routes/case-converter.tsx"),
  route("uppercase-converter", "routes/uppercase-converter.tsx"),
  route("lowercase-converter", "routes/lowercase-converter.tsx"),
  route("title-case-converter", "routes/title-case-converter.tsx"),
  route("sentence-case-converter", "routes/sentence-case-converter.tsx"),
  route("alternating-case-converter", "routes/alternating-case-converter.tsx"),
  route("text-cleaner", "routes/text-cleaner.tsx"),
  route("remove-extra-spaces", "routes/remove-extra-spaces.tsx"),
  route("whitespace-cleaner", "routes/whitespace-cleaner.tsx"),
  route("line-break-remover", "routes/line-break-remover.tsx"),
  route("remove-duplicate-lines", "routes/remove-duplicate-lines.tsx"),
  route("case-insensitive-sort", "routes/case-insensitive-sort.tsx"),
  route("base64-encode", "routes/base64-encode.tsx"),
  route("base64-decode", "routes/base64-decode.tsx"),
  route("url-encode", "routes/url-encode.tsx"),
  route("url-decode", "routes/url-decode.tsx"),
  route("text-case-checker", "routes/text-case-checker.tsx"),
  route("match-case-converter", "routes/match-case-converter.tsx"),
  route("ascii-to-text", "routes/ascii-to-text.tsx"),
  route("text-to-ascii", "routes/text-to-ascii.tsx"),
  route("json-to-text", "routes/json-to-text.tsx"),
  route("text-to-json", "routes/text-to-json.tsx"),
  route("xml-to-text", "routes/xml-to-text.tsx"),
  route("text-to-xml", "routes/text-to-xml.tsx"),
  route("sort-list", "routes/sort-list.tsx"),
  route("deduplicate-list", "routes/deduplicate-list.tsx"),
  route("html-to-text", "routes/html-to-text.tsx"),
  route("text-to-html", "routes/text-to-html.tsx"),
  route("comma-separated-to-list", "routes/comma-separated-to-list.tsx"),
  route("list-to-comma-separated", "routes/list-to-comma-separated.tsx"),
  route("list-to-table", "routes/list-to-table.tsx"),
  route("table-to-list", "routes/table-to-list.tsx"),
  route("comma-to-json-array", "routes/comma-to-json-array.tsx"),
  route("json-array-to-list", "routes/json-array-to-list.tsx"),
  route("text-to-comma-separated-list", "routes/text-to-comma-separated-list.tsx"),
  route("text-to-bulleted-text-list", "routes/text-to-bulleted-text-list.tsx"),
  route("text-to-ordered-list", "routes/text-to-ordered-list.tsx"),
  route("binary-to-text", "routes/binary-to-text.tsx"),
  route("text-to-binary", "routes/text-to-binary.tsx"),
  route("hex-to-text", "routes/hex-to-text.tsx"),
  route("text-to-hex", "routes/text-to-hex.tsx"),
  route("remove-all-styling-from-text", "routes/remove-all-styling-from-text.tsx"),
  route("text-to-pdf", "routes/text-to-pdf.tsx"),

  // Fallback
  route("*", "routes/not-found.tsx"),
  route("privacy-policy", "routes/privacy-policy.tsx"),
  route("terms-of-service", "routes/terms-of-service.tsx"),
  route("cookies-policy", "routes/cookies-policy.tsx"),
  route("contact", "routes/contact.tsx"),
  route("about", "routes/about.tsx"),
] satisfies RouteConfig;
